# Generated by Django 2.2.4 on 2019-12-08 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='title',
        ),
    ]
